version: '3'
services:
  db:
    ports:
      - 5432:5432
    environment:
      - NEXT_PUBLIC_NODE_ENV=development
  api:
    depends_on:
      - db
    command: sh -c "npm install -g nodemon && (npm run dev & nodemon -w package-lock.json --exec 'npm install')"
    stdin_open: true
    volumes:
      - ./src:/app/src
    ports:
      - ${NEXT_PUBLIC_API_PORT}:4000
    environment:
      - NEXT_PUBLIC_NODE_ENV=development
      - TYPEORM_LOGGING=true
  webclient:
    command: sh -c "npm install -g nodemon && (npm run dev & nodemon -w package-lock.json --exec 'npm install')"
    stdin_open: true
    volumes:
      - ./web-client:/app
      - /app/node_modules/
    ports:
      - ${NEXT_PUBLIC_WEB_CLIENT_PORT}:3000
    environment:
      - NEXT_PUBLIC_NODE_ENV=development
      - NEXT_PUBLIC_REACT_APP_API_PORT=${NEXT_PUBLIC_API_PORT}
