version: '3'

services:
  db:
    restart: always

  api:
    command: sh -c "npm run build && npm run start"
    expose:
      - 4000
    restart: always
    environment:
      - NEXT_PUBLIC_NODE_ENV=production

  webclient:
    command: sh -c "npm run build && npm run start"
    expose:
      - 3000
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_NODE_ENV=production
      - NEX_PUBLIC_REACT_APP_API_PORT=/api

  nginx:
    image: nginx:1.19.10
    restart: always
    stdin_open: true

    depends_on:
      - webclient
    ports:
      - ${NEXT_PUBLIC_GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
