version: '3'
services:
  db:
    image: postgres
    hostname: db
    container_name: db_container
    environment:
      - POSTGRES_PASSWORD=denver
  api:
    build: .
    hostname: api
    container_name: api_container
    depends_on:
      - db
    links:
      - db
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
      - TYPEORM_DATABASE=postgres
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=denver
  web-client:
    build: ./web-client
    hostname: web
    container_name: web_container
    links:
      - api
