version: '3'
services:
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=denver
      - POSTGRES_DB=postgres
  api:
    build: .
    depends_on:
      - db
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
      - TYPEORM_DATABASE=postgres
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=denver
  web-client:
    build: ./web-client
